---
title: "dashboard-zero"
author: "gsilvapt"
date: "December 13, 2015"
output: html_document
runtime: shiny
---

```{r, echo=FALSE}
library(shinyapps)
shinyapps::deployApp("~/Documents/dashboard-zero/dash-zero-shiny")
```

```{r, echo=FALSE}
source("source_from_repo.R")
### MAIN TABLE ###

### Number of unanswered inputs from volunteers in GitHub || 
### PULLS without answer at all ||
### PULL from volunteers with no activity for the last 7 days ||
### Number of open bugs |||
### Number of bugs needing triage |||
### Number of bugs by triage status |||
### Number of bugs assigned to expired Milestones |||

## pre-code for determine given variables
# For each of the above inputs
no_uiv <- sum(comments$creator != members$id && issues$comments_count)
p_noans <- sum(issues$is_pullrequest == "true" && issues$comments_count == 0)
p_noact <- sum(issues$is_pullrequest == "true" && issues$updated_date-7 == 0)
numb_bugs <- sum(repos$open_issues)

#num_bugs_triage <- sum(fromJSON("issues$url") != "labels")
#num_bugs_exp_mil <- sum(fromJSON("issues$issue_URL")

```